version: '3.8'

services:
  web:
    build: .
    ports:
      - "5003:5003"
    environment:
      - DATABASE_URL=postgresql://postgres:12345678@db:5432/pagos_bd
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - db
      - redis

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: pagos_bd
    ports:
      - "5432:5432"

  redis:
    image: redis:6
    ports:
      - "6379:6379"